name: OpenAI Codex PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  codex-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history for proper diff
          
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
                  
      - name: Get changed files
        id: changed-files
        run: |
          # Get the list of changed files in this PR
          git diff --name-only origin/${{ github.base_ref }}..HEAD > changed_files.txt
          echo "Changed files:"
          cat changed_files.txt
          
          # Store changed files as environment variable
          CHANGED_FILES=$(cat changed_files.txt | tr '\n' ' ')
          echo "changed_files=$CHANGED_FILES" >> $GITHUB_OUTPUT
          
      - name: Get file diffs
        run: |
          # Get the actual diff content for changed files
          git diff origin/${{ github.base_ref }}..HEAD > pr_diff.patch
          echo "PR Diff generated:"
          head -50 pr_diff.patch
          
      - name: Install Codex CLI
        run: npm install -g @openai/codex@latest

      - name: Run Codex CLI for PR review
        env:
          CODEX_HOME: ${{ github.workspace }}/.codex
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          # Create a comprehensive review prompt
          REVIEW_PROMPT="Please review this pull request. Here are the changed files and their modifications:
          
          Changed files: ${{ steps.changed-files.outputs.changed_files }}
          
          Please analyze the following diff and provide a code review with:
          1. Overall assessment of the changes
          2. Any potential issues or bugs
          3. Code quality and best practices feedback
          4. Security considerations if applicable
          5. Suggestions for improvement
          
          Here's the diff:
          $(cat pr_diff.patch)
          
          Please provide constructive feedback on these changes."
          
          codex exec --full-auto "$REVIEW_PROMPT"
          
      - name: Comment PR with review
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            // Get the Codex output (this would need to be captured from the previous step)
            const review = "Codex CLI review completed. Check the workflow logs for detailed feedback.";
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## 🤖 Codex CLI Code Review\n\n${review}\n\n*This review was automatically generated by OpenAI Codex CLI*`
            });